// Encounter art, part 2 (look A: pixel things on the trail). Row strings like the game's pixel
// icons: "." is empty, every other letter a colour from the palette. Creatures face left.
Object.assign(window.ENCOUNTER_SPRITES, {
  woods_log: { pal: { d: "#9c7a3c", b: "#d9b565", l: "#b8964f", w: "#ffe08a", r: "#c9a45c", k: "#1a1024", i: "#2c1d3d", h: "#8fe8c0", H: "#4f9c7c", p: "#ff79c6", s: "#a64f81", c: "#f5dcec", m: "#8fe8c0" }, rows: [
    "..................sps.....",
    ".................spppps...",
    ".....hhh..........scs.....",
    "...ddddddddddddhhHhdcddd..",
    "..dwwwwwdbbbbbbbbbbbbbbbd.",
    ".dwrrrrrwdbblbbbbbbblbbbbd",
    "dwrdddddrwdbbbbbblbbbbbbbd",
    "dwrdiiiidrwbbbbbbbbbbbbbbd",
    "dwrdikkidrwbblbbbbbbbblbbd",
    "dwrdikkidrwbbbbbbblbbbbbbd",
    "dwrdiiiidrwbbbbbbbbbbbbbbd",
    "dwrdddddrwdbbblbbbbbbbbbbd",
    ".dwrrrrrwdbbbbbbbblbbbbbbd",
    "..dwwwwwdbbbbbbbbbbbbbbbd.",
    "...dddddddddddddddddddddd.",
    "m.m..m...........m....m.m.",
    ".m..m.............m..m..m.",
  ] },
  woods_fox: { pal: { o: "#ffb38a", d: "#c7714f", D: "#8f4a35", w: "#fff1e6", k: "#1a1024", n: "#592a45", p: "#ff79c6", e: "#ffd9c2", c: "#8be9fd", f: "#8fe8c0", F: "#4f9c7c" }, rows: [
    "..d.....d..............",
    ".dod...dod.............",
    ".dpod.dpod.............",
    ".dpoodopod.............",
    ".doooooooood...........",
    "doooooooooood..........",
    "dokkoooookkod..........",
    "dokwoooookwod..........",
    "wwoooooooooowd.........",
    "nwwwwoooowwwwd.........",
    ".wwpwwwwwwwwd..........",
    "..dwwwwwwwwd......ddd..",
    "..doowwwwood.....dooodd",
    ".doooowwooood...doooowd",
    ".doooowwoooood.dooooowd",
    ".dooooowoooooodoooowwd.",
    ".dooooooooooooooooowwd.",
    ".doooooooooooooooowwd..",
    ".dwwodoooodooooooddd...",
    "..dwwdwwddwwddddd......",
    "f..dd.dd..dd......f.F..",
    "Ff.F.f...........fFf.f.",
  ] },
  pond_frog: { pal: { g: "#8fe8c0", G: "#4f9c7c", h: "#c8ffe6", w: "#fff1e6", k: "#1a1024", p: "#ff79c6", r: "#6f588c", R: "#4d3466", t: "#8f78ad", c: "#4fa9c9", C: "#8be9fd", b: "#2f6f8f", f: "#ff79c6", s: "#a64f81", y: "#d9b565" }, rows: [
    "..GGG..GGG..........y..",
    ".GwwwGGwwwG.........yf.",
    ".GkwwGGkwwG.........yff",
    ".GggggggggggG.......yf.",
    "GghhggggggggGG......y..",
    "GgpggggggggpgG......y..",
    "GGGGGGggggggggG.....y..",
    ".GgggggggggggggG....y..",
    "GgGggggggggggggGG...y..",
    "GG.GGGGGGGGGGgGGG..Ry..",
    "..RRRRRRRRRRRRRRRRRRRR.",
    ".RttrrrrrrrrrrrrrrrrrrR",
    "RrrrrrrrrrrrrrrrrrrrrrR",
    "bcccRRRRRRRRRRRRRRRRRcb",
    "bcCcccccbcccccCCcccccb.",
    ".bbccCCccccbbcccccbbb..",
  ] },
  pond_lilypads: { pal: { b: "#2f6f8f", c: "#4fa9c9", C: "#8be9fd", l: "#8fe8c0", L: "#4f9c7c", p: "#ff79c6", y: "#ffe08a", s: "#d9b565", S: "#9c7a3c", m: "#8fe8c0", M: "#4f9c7c" }, flat: true, rows: [
    "...........................p....",
    "..........................pyp...",
    "...........................M....",
    "........................mmmMmm..",
    ".......................mmmmmmmmm",
    "..bbbbbbbbbbbbbbbbbbbbSsssssssss",
    ".bccccccccLLLccccccLLcSSSSSSSSSS",
    "bccLLLLccLlllLccccLllLcccccCccb.",
    "bcLllllLcLllcLccccLLcccccccccb..",
    "bLllllcLccLLLcccCCccccccccccbb..",
    "bLlllllLcccccccccccccccccbbb....",
    ".bLLLLLcccCCccccbbbbbbbbbb......",
    "..bbbbbbbbbbbbbb................",
  ] },
  pond_reeds: { pal: { g: "#8fe8c0", G: "#4f9c7c", t: "#c7714f", T: "#8f4a35", w: "#fff1e6", k: "#1a1024", b: "#2f6f8f", c: "#4fa9c9", C: "#8be9fd", s: "#f5dcec" }, rows: [
    "....t........t.......",
    "...tTt..s...tTt......",
    "...tTt.....tTTt...t..",
    "...tTt..t..tTTt..tTt.",
    "...tTt.tTt.tTt...tTt.",
    "....G..tTt..G..s.tTt.",
    ".G..G..tTt..G.....G..",
    ".G..GG..G..GG..G..G..",
    ".GG.gG..G..Gg..G.GG..",
    "..G.gGG.GG.Gg.GG.G...",
    "..GgggGggGgggGgGgGG..",
    ".GgggwwgggggwwgggGG..",
    ".GggwkkwgggwkkwggGG..",
    "..GgwkkwgggwkkwggG...",
    ".GGggwwgggggwwgggGG..",
    ".GgggggGgggGgggGggG..",
    "GGgGggGGgGgGGggGgGGG.",
    "bcccccccCCcccccccCcb.",
    ".bccCCcccccccCCcccbb.",
  ] },
  pond_turtle: { pal: { g: "#8fe8c0", G: "#4f9c7c", l: "#c9a0ff", L: "#6f588c", D: "#4d3466", h: "#e4ccff", k: "#1a1024", w: "#fff1e6", y: "#ffe08a", p: "#ff79c6", m: "#8fe8c0" }, rows: [
    "..................y.......",
    "..........y......yyy......",
    ".........yyy......y.......",
    "..........y...LLLLLL......",
    ".............LlhllllLL....",
    "............LlhlLLllllL...",
    "..GGGG.....LllLDDLlllllL..",
    ".GggggG...LlllLDDLllLLllL.",
    "GgggggggG.LlLLllllllLDDlL.",
    "GgkkgggggGLLDDLllllllLLlL.",
    "Ggggggpgg.LlLLlllLLlllllL.",
    ".GGgggggGLLLLLLLLLLLLLLLLL",
    "..GwwGGgggggggggggggggggGG",
    "...ww.GggGGGGGGGGGGGggggG.",
    "......GggG.........GggG...",
    "......GGGG.........GGGG...",
    "m.m.............m.....m.m.",
  ] },
  stream_stones: { pal: { b: "#2f6f8f", c: "#4fa9c9", C: "#8be9fd", r: "#8f78ad", R: "#4d3466", t: "#b9a3d6", s: "#e8fbff", m: "#8fe8c0" }, flat: true, rows: [
    "............s.................",
    "...........sCs................",
    "..RRRR.....sRRR...RRRR...RRRR.",
    ".RttrrR..RCCrrR..RtrrrR.RtrrR.",
    ".RrrrrR..RCrrrR..RrrrrR.RrrrR.",
    "bRRRRRRbbRRRRRRbbRRRRRRbRRRRRb",
    "bcccCcccccccCCcccccccCcccccccb",
    "bccCCcccccCcccccccCCcccccCcccb",
    ".bbcccccbbbbccccCcccccbbbbbbb.",
  ] },
  stream_fish: { pal: { p: "#ff79c6", P: "#a64f81", e: "#ffd1ea", w: "#fff1e6", k: "#1a1024", y: "#ffe08a", b: "#2f6f8f", c: "#4fa9c9", C: "#8be9fd", s: "#e8fbff" }, rows: [
    "......................PP..",
    "..........PPPP.......PppP.",
    "........PPpppPPP....PpppP.",
    "......PPppppppppPP.PpppP..",
    ".....PpwwpppppppppPpppP...",
    "....PpwkkppppppppppppP....",
    "...PppwkkpppppyppppppP....",
    "..PppppwppppppppppppppP...",
    ".PPppppppppppppppPPpppP...",
    ".Pkeeeeeeeeeeeepp..PppP...",
    "..PPeeeeeeeeeeeP....PPP...",
    "....PPPPPPPPPPP...........",
    ".s...C......C......s......",
    "..C.....s........C........",
    "bccccCCccccccCCccccccCcb..",
    ".bbccccccbbbcccccCCccbb...",
  ] },
  stream_bottle: { pal: { g: "#bfefff", G: "#4fa9c9", h: "#ffffff", y: "#d9b565", Y: "#9c7a3c", n: "#fff1e6", N: "#c9b8d9", p: "#ff79c6", b: "#2f6f8f", c: "#4fa9c9", C: "#8be9fd" }, flat: true, rows: [
    ".............yy......",
    "............yYYy.....",
    "............GggG.....",
    "............GhgG.....",
    "...........GGggGG....",
    "..........GhggggGG...",
    ".........GgnnnnnggG..",
    "........GgnNpNNnngG..",
    ".......GgnNNNNNNngG..",
    "......GhgnnnnnnngG...",
    ".....GgggggggggGG....",
    "..C..GgggggggGG...C..",
    "bcccccGGGGGGGccccccb.",
    ".bccCCcccccccccCCcb..",
    "..bbbccccCCccccbbb...",
  ] },
  stream_waterfall: { pal: { r: "#8f78ad", R: "#4d3466", t: "#b9a3d6", g: "#8fe8c0", G: "#4f9c7c", c: "#4fa9c9", C: "#8be9fd", w: "#e8fbff", b: "#2f6f8f", y: "#ffe08a", Y: "#fff6d6" }, glow: true, rows: [
    "..GgG..............gGg....",
    ".GgggGG..........GGgggG...",
    "RRRRRRRbbbbbbbbbbbRRRRRRR.",
    "RtrrrRbcCcwCccCwcbRrrrtrR.",
    "RrrrRRbcCccCwccCcbRRrrrrR.",
    "RrrrRbccwcCccCccwcbRrrrRR.",
    "RrrRRbcCcccCcycCccbRRrrrR.",
    "RtrRbccCcwcCyYycCcwbRrrrR.",
    "RrrRbcwCccyYYYYyCccbRtrrR.",
    "RrRRbcCccCcyYYycCwcbRRrrR.",
    "RrRbccCcwcCcyccCcccbRrrrR.",
    "RrRbcwCcccCccCwcCccbRrrRR.",
    "RRRbcCccCcwCccCcCwcbRRrrR.",
    "RrRbcCcwCccCccwCcCcbRrrrR.",
    "RRbccCccCcccCccCccwcbRrrR.",
    "RrbcwCcccCwcCccCcCccbRRrR.",
    "RRbcCccwCccCcwccCccCbRrrR.",
    ".w.bCcwCcwCcCwcCcwCb.w.w..",
    "w.bwwCwwCwwwCwwCwwCwb..w..",
    ".bbwcwwcwwcwwcwwcwwwcbb...",
    "bccccccCCccccccCCcccccccb.",
    ".bbcccccccbbbbcccccccbbb..",
  ] },
  shed_boxes: { pal: { b: "#d9b565", B: "#9c7a3c", h: "#ffe08a", t: "#b8964f", p: "#ff79c6", P: "#a64f81", k: "#1a1024", d: "#c9b8d9", s: "#6f588c" }, rows: [
    "...d.......d.........",
    ".....BBBBBBBBBB..d...",
    "....BpPbbbbbbPpB.....",
    "....BbpPbbbbPpbB.....",
    "..d.BbbpPbbPpbbB.....",
    "....BbbbpPPpbbbB.....",
    "....BbbbPppPbbbB.d...",
    "....BbbPpbbpPbbB.....",
    "....BBBBBBBBBBBB.....",
    "..BBBBBBBBBBBBBBB....",
    "..BhbbbbbBBbbbbbB....",
    "..BbbbbbbtBbbbbbB....",
    "..BbbbbbbBBbbbbbB....",
    "..BbbbbbbbbbbbtbB....",
    "..BBBBBBBBBBBBBBB....",
    ".....BBBBBBBBBBBBBBB.",
    ".....BhbbbbbBBbbbbbB.",
    ".....BbbbbbbtBbbbbbB.",
    "BBBBBBBBBBBBBBBbbbbB.",
    "BhbbbbbBBbbbbBBbbtbB.",
    "BbbbbbbtBbbbbbBBBBBB.",
    "BbbbbbbBBbbbbbB......",
    "BbbtbbbbbbbbbbB......",
    "BBBBBBBBBBBBBBB......",
    "..s.s.......s..s.....",
  ] },
  shed_spider: { pal: { l: "#c9a0ff", L: "#6f588c", D: "#4d3466", h: "#e4ccff", k: "#1a1024", w: "#fff1e6", p: "#ff79c6", m: "#8fe8c0", e: "#9d86bd" }, rows: [
    "............LLLL............",
    ".........LLLllllLLL.........",
    "........LlhhlllllllL........",
    ".e.....LlhklklllllllL.....e.",
    ".eeeeeeLllllllllllllLeeeeee.",
    ".e.e...LlwklwkllllllL...e.e.",
    ".e.eeeeLlkklkkllllllLeeee.e.",
    ".e.e.e.LplllllplllllL.e.e.e.",
    ".e.e.eeeLlwlwllllllLeee.e.e.",
    ".e.e.e...LLLllllLLL...e.e.e.",
    ".e.e.e....e.LLLL.e....e.e.e.",
    ".e.e.e....e......e....e.e.e.",
    ".e.e.e....e......e....e.e.e.",
    "m..........................m",
    ".m........................m.",
  ] },
});
