// Encounter art, part 4: shared events and the underground ones. Row strings, "." is empty.
Object.assign(window.ENCOUNTER_SPRITES, {
  goose: {"alias": "garden_goose"},
  fox: {"alias": "woods_fox"},
  chest: {"pal": {"d": "#4d3466",
    "l": "#6f588c",
    "h": "#c9a0ff",
    "g": "#ffe08a",
    "y": "#d9b565",
    "w": "#fff1e6",
    "k": "#1a1024",
    "m": "#8fe8c0"}, "rows": [
    "..............w...",
    ".............www..",
    "..............w...",
    "..dddddddddddd....",
    ".dhllllllllllld...",
    ".dyyyyyyyyyyyyd...",
    "..gwgggggggwggg...",
    ".dyyyyyygyyyyyd...",
    ".dhlllllgkglllld..",
    ".dllllllgggllld...",
    ".dllllllllllllld..",
    ".dyyyyyyyyyyyyd...",
    "m.m..........m.m..",
  ]},
  limping: {"pal": {"P": "#a64f81",
    "p": "#ff79c6",
    "w": "#ffd1ea",
    "b": "#ffb38a",
    "B": "#c7714f",
    "c": "#fff1e6",
    "d": "#8be9fd",
    "D": "#4fa9c9",
    "m": "#8fe8c0"}, "rows": [
    "...PPP....PPP..d..",
    "..PpppP..PpppP.ddd",
    "..PpwpP..PpwpP.dDd",
    "..PpppP..PpppP..D.",
    ".PPP.PPP..PPP.PPP.",
    "PpppP........PpppP",
    "PpwpP..PPPP..PpwpP",
    ".PPP.PPppppPP.PPP.",
    "....PppppppppP....",
    "..BBbbbbbbbbbbBB..",
    "..BBbcbbcbbcbbBB..",
    "...PppppppppppP...",
    "....PPppppppPP....",
    "......PPPPPP......",
    "m.m...........m.m.",
  ]},
  puddle: {"flat": true, "pal": {"m": "#7a5a4a",
    "M": "#5a3f36",
    "c": "#8be9fd",
    "C": "#4fa9c9",
    "l": "#6f588c",
    "g": "#8fe8c0"}, "rows": [
    ".....MMMMMMMMMM.......",
    "..MMMmmmmmmmmmmMMM....",
    ".MmmmmmCCCCmmmmmmmM...",
    "MmmmCCCccCCCmmmmmmmM..",
    "MmmmmCCCCCCmmmmcmmmM..",
    ".MMmmmmmmmmmmmmmmMM.g.",
    "...MMMMMMMMMMMMMM..g.g",
  ]},
  hill: {"pal": {"g": "#8fe8c0",
    "G": "#4f9c7c",
    "h": "#c9f5df",
    "p": "#ff79c6",
    "P": "#a64f81",
    "s": "#9c7a3c",
    "y": "#ffe08a"}, "rows": [
    "..............pp..............",
    "..............ppp.............",
    "..............pppp............",
    "..............pP..............",
    "..............s...............",
    "..............s...............",
    "..........GGGGsGGGG...........",
    ".......GGGhhhgsgggggGGG.......",
    ".....GGghhhggggggggggggGG.....",
    "....GghhgggggggggggggggggG....",
    "...GghggggggggggyggggggggG....",
    "..GgggggggggggggggggggggggG...",
    "..GgggyggggggggggggggggggggG..",
    ".GgggggggggggggggggggggpgggG..",
    ".GggggggggggggggggggggggggggG.",
    "GgggggggggggggGgggggggggggggG.",
    "GggggggggggggGgGgggggyggggggG.",
    "GgggggggggggggggggggggggggggG.",
    "GGGGGGGGGGGGGGGGGGGGGGGGGGGGG.",
  ]},
  tracks: {"flat": true, "pal": {"t": "#9a88ad",
    "T": "#6f588c",
    "g": "#8fe8c0"}, "rows": [
    ".........................t.t..",
    "........................t...t.",
    ".........................ttt..",
    ".................t.t.....ttt..",
    "................t...t.........",
    ".................ttt..........",
    ".........t.t.....ttt..........",
    "........t...t.................",
    ".t.t.....ttt..................",
    "t...t....ttt..................",
    ".ttt..........................",
    ".ttt.....g.g..........g.g.....",
  ]},
  signpost: {"pal": {"w": "#d9b565",
    "d": "#9c7a3c",
    "D": "#6b5230",
    "f": "#b8a07a",
    "g": "#8fe8c0",
    "h": "#ffe08a"}, "rows": [
    ".......dd.........",
    "..dddddddddddd....",
    ".dhwwwwwwwwwwwd...",
    "dwwfwffwwfwfwwwd..",
    ".dwwwwwwwwwwwwd...",
    "..dddddwwdddddd...",
    ".......wd.........",
    ".....dddddddddd...",
    "....dwwwwwwwwwhd..",
    "...dwwwffwfwffwwd.",
    "....dwwwwwwwwwwd..",
    ".....ddddwwdddd...",
    ".......dwwd.......",
    ".......dwwd.......",
    ".......dwwd.......",
    ".....g.dwwd.g.g...",
    "....g.gDDDDg.g....",
  ]},
  dark: {"eerie": true, "pal": {"b": "#120a19",
    "B": "#2e1f3d",
    "y": "#ffe08a",
    "Y": "#d9b565",
    "p": "#ff4f9a",
    "k": "#1a1024",
    "l": "#4d3466"}, "rows": [
    "........BBBBBBBB........",
    ".....BBBbbbbbbbbBBB.....",
    "...BBbbbbbbbbbbbbbbBB...",
    "..Bbbbbp.pbbbbbbbbbbbB..",
    ".Bbbbbbbbbbbbbbbb.p.pbB.",
    ".BbbbyyybbbbbyyybbbbbbB.",
    "BbbbyyyyybbbyyyyybbbbbbB",
    "BbbbykyyybbbykyyybbbbbbB",
    "BbbbyyyyybbbyyyyybbbbbbB",
    "BbbbbyyybbbbbyyybbbbbbbB",
    ".Bbbbbbbbbbbbbbbbbp.pbB.",
    ".Bbp.pbbbbbbbbbbbbbbbbB.",
    "..BbbbbbbbbbbbbbbbbbbB..",
    "...BBbbBbbbbbbBbbbbBB...",
    ".....BB.BBbbBB.BBBB.....",
  ]},
  rope: {"flat": true, "pal": {"R": "#9c7a3c",
    "r": "#d9b565",
    "h": "#ffe08a",
    "W": "#6b5230",
    "w": "#9c7a3c",
    "S": "#2e1f3d",
    "s": "#4d3466",
    "b": "#0a0510"}, "rows": [
    "..W.................",
    ".WwW................",
    ".WhWrr..............",
    ".WwWRrhr............",
    ".WwW..Rrr...........",
    ".WwW....Rr..........",
    ".WwW.....rR.........",
    ".WwW......Rr........",
    ".WwW.......rR.......",
    ".WwW..SSSSSRrSSS....",
    ".WwWSSsssbbrRbbsSS..",
    "SSSSssbbbbbRrbbbbssS",
    "SssbbbbbbbbrRbbbbbsS",
    ".SssbbbbbbbbbbbbbssS",
    "..SSssssssssssssSS..",
    "....SSSSSSSSSSSS....",
  ]},
  door: {"pal": {"s": "#4d3466",
    "S": "#2e1f3d",
    "h": "#6f588c",
    "w": "#9c7a3c",
    "W": "#6b5230",
    "y": "#ffe08a",
    "g": "#ff4f9a",
    "k": "#d9b565"}, "rows": [
    "SSSSSSSSSSSSSSSSSSSS",
    "SsshSsssSssshSsssSsS",
    "SSSSSSSSSSSSSSSSSSSS",
    "SssSsssWWWWWWsSsssSS",
    "SSSSSWWwwwwwwWWSSSSS",
    "SshSWwwwWwwWwwwWSsSS",
    "SSSWwwwwWwwWwwwwWSSS",
    "SssWwwwwWwwWwwwwWsgS",
    "SSSWwwwwWwwWwwkwWSSg",
    "SshWwwwwWwwWwwwwWsgS",
    "SSSWwwwwWwwWwwwwWSSS",
    "SssWwwwwWwwWwwwwWshS",
    "SSSWwwwwWwwWwwwwWSSS",
    "SyyyyyyyyyyyyyyyyyyS",
  ]},
  thing: {"eerie": true, "pal": {"b": "#2e1f3d",
    "B": "#1c1228",
    "h": "#4d3466",
    "k": "#9a88ad",
    "p": "#ff4f9a",
    "z": "#c9a0ff",
    "m": "#a64f81"}, "rows": [
    "..........................zzzz..",
    "............................z...",
    "...........................z..zz",
    "..........................zzzz.z",
    "..............................z.",
    "..........BBBBBBBBBBB.........zz",
    "......BBBBbbbbbbbbbbbBBBB.......",
    "....BBbbbbhhhbbbbbbbbbbbbBB.....",
    "...Bbbbbhhhbbbbbbbbbbbbbbbb.....",
    "..Bbbbbhhbbbbbbbbbbbbbbbbbbb....",
    ".Bbbbbbbbbbbbbbbbbbbbbbbbbbbb...",
    ".BbbbkkkbbbbbkkkbbbbbbbbbbbbB...",
    "BbbbbbbbbbbbbbbbbbbbbbbbbbbbbB..",
    "BbbmmbbbbbbbbbbbbmmbbbbbbbbbbB..",
    "BbbbbbbbbbpbbpbbbbbbbbbbbbbbbbB.",
    "BbbbbbbbbbbppbbbbbbbbbbbbbbbbbB.",
    "BbbbbbbbbbbbbbbbbbbbbbbbbbbbbbB.",
    ".BbbbbbbbbbbbbbbbbbbbbbbbbbbbB..",
    "..BBbbbBBbbbbbbbbbbbbbBBbbbBB...",
    "....BBB..BBBBBBBBBBBBB..BBB.....",
  ]},
});
