// Encounter art, part 3: the shed's jar and mice, the garden path, and the shared fork and brambles.
// Look A (pixel things on the trail). Rows are pixels; '.' is empty, other letters come from pal.
// Made with a small script; hand-tune freely.
Object.assign(window.ENCOUNTER_SPRITES, {
  shed_jar: { pal: {"G": "#d9b565", "g": "#ffe08a", "c": "#4fa9c9", "w": "#b8ecf7", "p": "#ff79c6", "P": "#a64f81", "m": "#8fe8c0", "M": "#4f9c7c", "l": "#c9a0ff", "L": "#6f588c", "y": "#ffb38a", "Y": "#c7714f", "h": "#d9b565", "D": "#9c7a3c"}, float: 34, rows: [
    ".......GGGGGG.......",
    "......GggggggG......",
    "......GGGGGGGG......",
    ".......cc..cc.......",
    ".....ccc....ccc.....",
    ".....cw.pp.gg.c.....",
    ".....cw.pP.gG.c.....",
    ".....cwmm.ll.yc.....",
    ".....c.mM.lL.Yc.....",
    ".....cgg.pp.mmc.....",
    ".....cgG.pP.mMc.....",
    ".....c.ll.yy.pc.....",
    ".....cwlL.yY.Pc.....",
    "......cccccccc......",
    "hhhhhhhhhhhhhhhhhhhh",
    "DDDDDDDDDDDDDDDDDDDD",
    "..DD............DD..",
    "..D..............D..",
    "..D..............D..",
    "....................",
    "....................",
  ] },
  shed_mice: { pal: {"b": "#c7714f", "B": "#8a4a36", "h": "#e0946b", "D": "#5c3226", "c": "#fff1e6", "g": "#ffe08a", "k": "#1a1024", "y": "#d9b565", "e": "#ff79c6", "t": "#c9b8d9", "n": "#ff79c6", "m": "#8fe8c0"}, rows: [
    "......................",
    "...............e...e..",
    "............e..ettte..",
    "............etttktkt..",
    "............tktktnt...",
    ".............tntttt...",
    "............BBBBBBB...",
    "............BhhhhhB...",
    "............BbbbbbB...",
    "............BcbcbbB...",
    "............BbcbbbB...",
    ".....BBBBBBBbcbcbbB...",
    "..BhBbbbbbbbbbcbbbB...",
    ".BhhbbbbbbbbbcbgggB...",
    "BbbbbbbbbbbbbbcgkyB...",
    ".BbbbbbbbbbbbbbgggB...",
    ".BBbbbbbbbbbbbbbbbB...",
    "...DDDDDDDDDDDDDDDD...",
    "m.m..............m.m..",
  ] },
  garden_fork: { pal: {"b": "#9c7a3c", "B": "#6b5228", "h": "#d9b565", "p": "#ff79c6", "w": "#fff1e6", "y": "#ffe08a", "a": "#d9b565", "g": "#8fe8c0", "V": "#8f76b3", "v": "#6f588c", "n": "#120a19"}, rows: [
    "....................................",
    "....................................",
    "....................................",
    "......BBBBBBBBBBB...................",
    ".....BhhhhhhhhhBB...................",
    "....BhhphyhhhhhBB...................",
    ".....BhhhhhhhhhBB...................",
    "......BBBBBBBBBBB............vvvvv..",
    "..............BbB...........vnVVVnv.",
    "..............BBBBBBBBBBB..vnVnnnVnv",
    "..............BBhhhhhhhhhB.vVnnvnnVv",
    "..............BBhhhhhhhhhhvnVnvnvnVn",
    "..............BBhhhhhhhhhBvnnVnnvVnv",
    "..............BBBBBBBBBBB.vnnnVVnnnv",
    "..............BbB.........vnVnnnnnVv",
    ".p...y........BbB.........vVvVnnnVvv",
    "pwp.yay.......BbB.........VnnvVVvnVv",
    ".p...y........BbB.........VnvnnnvnVv",
    ".g..pg........BbB.....V...vVnnvnnVnv",
    ".g.pwp.g......BbB......V.VvnVVvVVnnv",
    "gg.gp.gg......BbB.......V.vVnnnnnVnv",
    "..............BBB.........vvvvvvvvvv",
  ] },
  garden_brambles: { pal: {"v": "#4f9c7c", "V": "#2f7a5c", "t": "#c9a0ff", "g": "#8fe8c0", "r": "#ff4f6a", "R": "#b8334a", "w": "#fff1e6", "s": "#ffe08a", "m": "#8fe8c0"}, rows: [
    "........................",
    "......t.......t.........",
    ".....vVv....vVVv...t....",
    "...tv...v..v....v.vVv...",
    "...v..g..vv..gg..v...v..",
    "..v..gg..Vvs....vv.g..v.",
    ".tv.....s..V...V..vgg.vt",
    ".v...vVV....VVs.....v..v",
    "v...v.....RR.....v...v.v",
    "v..v.g...RrwR....v.g..v.",
    "Vv.v.ggs.RrrR...v..gg.vV",
    ".VvV......RR....VvvVvVV.",
    "..VVvVVvVVvvVVvVV..VV...",
    "m.m..................m.m",
  ] },
  garden_goose: { pal: {"w": "#fff1e6", "S": "#8a7f99", "s": "#c9b8d9", "k": "#1a1024", "o": "#ffb38a", "O": "#c7714f", "m": "#8fe8c0"}, rows: [
    "....SSSS...............",
    "...SwwwwS..............",
    "..SSSwwwwS.............",
    "ooSwkwwwwS.............",
    "OOSwwwwwwS.............",
    "...SwwwwS..............",
    "....SwwwS..............",
    ".....SwwS..............",
    ".....SwwS..............",
    ".....SwwS..............",
    ".....SwwS..............",
    ".....SwwS..............",
    ".....SwwS..............",
    ".....SwwS..............",
    ".....SwwS..............",
    ".....SwwS..SSSSS..SSS..",
    ".....SwwSSSwwwwwSSwwwS.",
    ".......SwwwwsssssssssS.",
    "......SwwwwsssssssssS..",
    ".....SwwwwwsswwwwwsssS.",
    ".....SwwwwwwwwwwwwwwsS.",
    ".....SwwwwwwwwwwwwwwwS.",
    "......SwwwwwwwwwwwwwS..",
    ".......SwwwwwwwwwwwS...",
    "........SSSwwwwwSSS....",
    ".........ooSSooS.......",
    ".........OOO.OOO.......",
    "m.m.................m.m",
  ] },
  garden_chest: { pal: {"d": "#4d3466", "l": "#6f588c", "h": "#8f76b3", "s": "#5a4478", "g": "#ffe08a", "G": "#d9b565", "k": "#1a1024", "p": "#ff79c6", "m": "#8fe8c0"}, rows: [
    "................pppp.",
    "................p..p.",
    "...........p....p..p.",
    "...........pp..pp.pp.",
    "...........p...pp.pp.",
    "...dddddddddddd......",
    "..dhhhhhhhhhhhhd.....",
    ".dllllllllllllllld...",
    ".GggggggggggggggG....",
    ".dlllllgkkgllllld....",
    ".dlllllggggllllld....",
    ".dllllllllllllllld...",
    ".dssssssssssssssd....",
    ".GggggggggggggggG....",
    "..dddddddddddddd.....",
    "mm.m..........m.m....",
  ] },
  garden_apples: { pal: {"b": "#c7714f", "B": "#8a4a36", "G": "#4f9c7c", "D": "#2f5c4c", "g": "#8fe8c0", "r": "#ff4f6a", "R": "#b8334a", "w": "#ffd1ea", "y": "#ffe08a", "Y": "#d9b565", "s": "#fff6d6", "m": "#8fe8c0"}, rows: [
    "..............b..s..........",
    "..........s..yyw............",
    ".............yyY............",
    "..........DsDDYDDDs.........",
    ".........DGGGgGGGGGD........",
    "........DGGGGGGGGGGgD.......",
    ".......DGGGGGGgGGGGGGD......",
    ".......DGgGGGGGGGGGGgD......",
    "......DGGGGGGGGgGGGGGGD.....",
    "....DDGGGGgGGGGGGGGGGgGDD...",
    "....DgGGGGGGGGGGgGGrwGGGD...",
    "...DGGGGrwGgGGGGGGGrRGgGGD..",
    "...DGGgGrRGGGGGGGgGGGGGGGD..",
    "..DGGGGGGGGGgGGGGGGGGGGgGGD.",
    "..DGGGGgGGGGGGGGGGgGGGrwGGD.",
    ".DgGGGGGGGGGGgrwGGGGGGrRgGGD",
    "..DGGrwGgGGGGGrRGGGgGGGGGGD.",
    "..DgGrRGGGGGGGgGGGrwGGGGGgD.",
    "...DGGGGGgrwGGGGGGrRgGGGGD..",
    "....DDDGDDrRGGGgGGGDDGDDD...",
    ".......D..DDDDDDDDD..D......",
    "............BbbB............",
    "............BbbB............",
    "............BbbB............",
    "............BbbB............",
    "............BbbB............",
    "............BbbB............",
    "..........BBBBBBBB..........",
    "..m.m.................m.m...",
    "...m...................m....",
  ] },
  garden_bees: { pal: {"b": "#c7714f", "B": "#8a4a36", "G": "#4f9c7c", "D": "#2f5c4c", "y": "#ffe08a", "Y": "#d9b565", "O": "#9c7a3c", "k": "#1a1024", "h": "#ffc857", "w": "#e8fbff", "m": "#8fe8c0"}, rows: [
    "...DDDDD....................",
    ".DDGGGGGDD..................",
    "DGGGGGGGGGD.................",
    "DGGGGGGGGGD.................",
    "GGGGGGGGGGGD................",
    "DGGGGGGGGGD.................",
    "DGGGGGGGGGD.................",
    ".DDGGGGBBBBBBBBBBBBBBB......",
    "...DDDDBBBBBBBBBBBBBBB......",
    "...BbbB.........BB..........",
    "...BbbB........OOOOO.....ww.",
    "...BbbB.......OyyyyyO...yky.",
    "...BbbB...ww.OYYYYYYYO......",
    "...BbbB..ykyOyyyyyyyyyO.....",
    "...BbbB.....OyyyyyyyyyO.....",
    "...BbbB.....OYYYYYYYYYO.....",
    "...BbbB.....OyyyyyyyyyO.....",
    "...BbbB.....OyyykkyyyyO.....",
    "...BbbB....wwOYYYYYYYO......",
    "...BbbB...yky.OyyyyyO...ww..",
    "...BbbB........OOhOO...yky..",
    "...BbbB........h.h.h........",
    "...BbbB........h...h........",
    "...BbbB............h........",
    "...BbbB.....................",
    "...BbbB.....................",
    "...BbbB.....................",
    "..BBBBBB.......hhhhhh.......",
    "mm.m......................m.",
  ] },
  garden_ball: { pal: {"p": "#ff79c6", "P": "#a64f81", "s": "#d4559f", "c": "#8be9fd", "w": "#fff1e6", "m": "#8fe8c0"}, rows: [
    "................",
    "......PPPP......",
    "....wwppppPP....",
    "...PwcppppppP...",
    "...PccppppppP...",
    "..PpcccppppppP..",
    "..PppccppppppP..",
    "..PppcccpppppP..",
    "..PpppccppppsP..",
    "...PppcccppsP...",
    "...PpppccpspP...",
    "....PPpcccPP....",
    "......PPPP......",
    "m.m.........m.m.",
    ".m...........m..",
  ] },
  garden_pond: { pal: {"b": "#4fa9c9", "d": "#35708c", "o": "#2f5c4c", "c": "#8be9fd", "y": "#ffe08a", "w": "#fff6d6", "s": "#c9b8d9", "k": "#1a1024", "m": "#8fe8c0", "q": "#ffb38a"}, flat: true, rows: [
    "...............................",
    "...............................",
    "...............................",
    "......sss......................",
    ".....swkws........sss..........",
    "....qqwwws..s....swkws.........",
    "......swwwssw..oqqwwws..s......",
    "......swwwwwsoobooswwwssw......",
    "....ooobbbbbbbbbbbswwwwwsoo....",
    "..ooccccbbbbbbbbbbbbbbbbbbboo..",
    ".obbbbbbbbdddddddddddbcccbbbbo.",
    ".obbbbbdddddddddddddydddbbbbbm.",
    "mobbbbdddddddddddddywsdddbbbbom",
    "m.oobbbdddddddddddddydddbbboo..",
    "....ooobbcccdddddddddbbbooo....",
    ".......ooooooooboooooooo.......",
    "...............o...............",
  ] },
  fork: { pal: {"b": "#9c7a3c", "B": "#6b5228", "h": "#d9b565", "p": "#ff79c6", "w": "#fff1e6", "y": "#ffe08a", "a": "#d9b565", "g": "#8fe8c0", "G": "#4f9c7c", "D": "#2f5c4c"}, rows: [
    "....................................",
    "....................................",
    "....................................",
    "......BBBBBBBBBBB...................",
    ".....BhhhhhhhhhBB...................",
    "....BhhphyhhhhhBB........DDDDDDDDDD.",
    ".....BhhhhhhhhhBB.......DgGGGGGGgGGD",
    "......BBBBBBBBBBB.......DGGGgGGGGGGD",
    "..............BbB.......DGGGGGGgGGGD",
    "..............BBBBBBBBBBBDGgGGGGGGgD",
    "..............BBhhhhhhhhhDGGGGgGGGGD",
    "..............BBhhhhhhhhhDgGGGGGGgGD",
    "..............BBhhhhhhhhhDGGGgGGGGGD",
    "..............BBBBBBBBBBBDGGGGGGgGGD",
    "..............BbB........DGGgGGGGGGD",
    ".p...y........BbB........DGGGGGgGGGD",
    "pwp.yay.......BbB........DGgGGGGGGgD",
    ".p...y........BbB........DGGGGgGGGGD",
    ".g..pg........BbB........DgGGGGGGgGD",
    ".g.pwp.g......BbB........DGGGgGGGGGD",
    "gg.gp.gg......BbB........DGGGGGGgGGD",
    "..............BBB........DDDDDDDDDDD",
  ] },
  brambles: { pal: {"v": "#4f9c7c", "V": "#2f7a5c", "t": "#c9a0ff", "g": "#8fe8c0", "m": "#8fe8c0"}, rows: [
    "...................................",
    "......t.......t..t.......t.........",
    ".....vVv....vVVvvVvt...vVVv...t....",
    "...tv...v..v..tvv.vvv.v....v.vVv...",
    "...v..g..vv..gv..g..vv..gg..v...v..",
    "..v..gg..Vv..v..gg.gVvv....vv.g..v.",
    ".tv.....V..Vtv.V..vVg.Vt..V..vgg.vt",
    ".v...vVV....vVV.vVV.v..VVV.....v..v",
    "v...v......v...v.v...v.v....v...v.v",
    "v..v.g.....v..v.gv.g..v.....v.g..v.",
    "Vv.v.gg....Vv.v.gg.gg.vV...v..gg.vV",
    ".VvV........VvV.VvvVvVV....VvvVvVV.",
    "..VVvVVvVVvvVVVvVVvVVvvVVvVV..VV...",
    "m.m.............................m.m",
  ] },
});
