// Encounter art, part 1 (look A): pixel things on the trail. Rows of letters, colours in pal.
Object.assign(window.ENCOUNTER_SPRITES, {
  meadow_basket: { pal: {"d": "#9c7a3c", "g": "#ffe08a", "w": "#d9b565", "h": "#c9a0ff", "m": "#8fe8c0", "p": "#ff79c6", "q": "#a64f81"}, rows: [
    "......hhhhhhhh......",
    ".....h........h.....",
    "....h..........h....",
    "....h.......pp.h....",
    ".dddddddddddpqddddd.",
    ".dggggggggggggggggd.",
    "..dwgwgwgwgwgwgwgd..",
    "..dgwgwgwgwgwgwgwd..",
    "..dwgwgwgwgwgwgwgd..",
    "...dgwgwgwgwgwgwd...",
    "...dwgwgwgwgwgwgd...",
    "....dddddddddddd....",
    "m.m..............m.m",
    ".m................m.",
  ] },
  woods_cart: { pal: {"d": "#9c7a3c", "l": "#d9b565", "w": "#ffe08a", "t": "#b8903f", "h": "#c7714f", "o": "#6f588c", "k": "#c9a0ff", "u": "#4d3466", "v": "#6f588c", "p": "#ffb38a", "m": "#8fe8c0"}, rows: [
    ".....p..m....p...m....p..",
    "...dddddddddddddddddddd..",
    "...dwllltlllltlllltllld..",
    "hhhdlllltlllltlllltllld..",
    "...dlllltlllltlllltllld..",
    "...dddoooddddddddoooddd..",
    ".....o.k.o......o.k.o....",
    "....o..k..o....o..k..o...",
    "....okkkkko....okkkkko...",
    ".uuuuuuuuuuuuuuuuuuuuuuu.",
    "uuvuuuuuvuuuuuuuvuuuuuvuu",
    "..uuuuuuuuuuuuuuuuuuuuu..",
  ] },
  orchard_wheelbarrow: { pal: {"s": "#a64f81", "p": "#ff79c6", "w": "#ffd1ea", "h": "#c7714f", "o": "#6f588c", "k": "#c9a0ff", "c": "#f5dcec", "m": "#8fe8c0"}, rows: [
    ".......................hh",
    "......................h..",
    ".....sssssssssssssssshs..",
    ".....spwwppppppppppppps..",
    "......sppppppppppppppps..",
    ".c.....sppppppppppppps...",
    "c.....ooosssssssssssss...",
    ".....o.k.o........h......",
    "c...o..k..o.......h......",
    ".c..okkhhhhhhhhhhhhhhh...",
    "....o..k..o.......h......",
    ".....o.k.o........hh.....",
    "..m.m.omo.....m.m.m......",
  ] },
  meadow_wagon: { pal: {"y": "#9c7a3c", "g": "#ffe08a", "h": "#d9b565", "d": "#c7714f", "w": "#ffb38a", "t": "#fff1e6", "o": "#6f588c", "k": "#c9a0ff", "m": "#8fe8c0"}, rows: [
    ".......g...g....g..g..........",
    ".....ygyyyygyyyyyygyyy........",
    "....ygghggggghggggghgggy......",
    "...yggggghgggggggghggggggy....",
    "..ddddddddddddddddddddddddd...",
    "..dtwwwwwwwwwwwwwwwwwwwwwwd...",
    "..dwwdwwwwwdwwwwwdwwwwwdwwd...",
    "..dwwdwwwwwdwwwwwdwwwwwdwwd...",
    "..dwwwwwwwwwwwwwwwwwwwwwwwd...",
    "dddddddddddddddddddddddddddd..",
    "....ooo..............ooo......",
    "...o.k.o............o.k.o.....",
    "..o..k..o..........o..k..o....",
    "..okkkkko..........okkkkko....",
    "..o..k..o..........o..k..o....",
    "...o.k.o............o.k.o.....",
    ".m..ooo.m..m.....m...ooo..m...",
  ] },
  orchard_piggy: { pal: {"s": "#a64f81", "p": "#ffb3dd", "n": "#ff79c6", "e": "#1a1024", "w": "#fff1e6", "k": "#592a45", "y": "#ffe08a", "c": "#f5dcec", "r": "#6f588c", "q": "#4d3466", "m": "#8fe8c0"}, rows: [
    "............c.y.c...",
    ".............yyy....",
    "....s.......c.y.c...",
    "...sps..ssssssss....",
    "..spppsspppkkkppss..",
    ".sppeppppppppppppwps",
    ".sppeppppppppppppps.",
    "snnspppppppppppppps.",
    "snnspppppppppppppps.",
    "sssppppppppppppppps.",
    "..spppppppppppppps..",
    "..sps.sps..sps.sps..",
    "rrqr..rq.rrrqr.rqrrr",
    "qrrrrqrrrrqrrrrrrqrr",
  ] },
  fields_cushion: { pal: {"o": "#6f588c", "p": "#c9a0ff", "w": "#e8d6ff", "b": "#ff79c6", "t": "#ffe08a", "m": "#8fe8c0"}, rows: [
    "t.oooooooooooooooo.t",
    ".toppppppppppppppot.",
    ".oppwwppppppppwwppo.",
    ".opwppppppppppppwpo.",
    "oppppppppppppppppppo",
    "oppppppppbbppppppppo",
    "oppppppppppppppppppo",
    ".oppppppppppppppppo.",
    ".ooppppppppppppppoo.",
    ".toooooooooooooot...",
    "t..................t",
    "m.m.m..............m",
  ] },
  meadow_butterflies: { glow: true, float: 26, pal: {"p": "#ff79c6", "l": "#c9a0ff", "m": "#8fe8c0", "c": "#8be9fd", "y": "#ffe08a", "w": "#fff1e6", "k": "#4d3466"}, rows: [
    "..........................",
    "pp.pp.............ll.ll...",
    "ppkpp.............llkll...",
    ".pkp...............lkl....",
    "............w.............",
    "..........w.cc.cc.w.......",
    "....mm.mm...cwkwc.........",
    "....mmkmm...cckcc.........",
    ".....mkm.....ckc....pp.pp.",
    "............y...y...ppkpp.",
    ".....................pkp..",
    "..ll.ll.......w...........",
    "..llkll...................",
    "...lkl....................",
  ] },
  meadow_hay: { pal: {"y": "#9c7a3c", "g": "#ffe08a", "h": "#d9b565", "l": "#c9a0ff", "p": "#ff79c6", "w": "#ffd1ea", "k": "#a64f81", "c": "#f5dcec", "m": "#8fe8c0"}, rows: [
    "...........c..k..c..",
    "............ppp.....",
    "..........c.pwp.c...",
    "...........ppppp....",
    "..yyyyyyyyyyyyyyyyy.",
    ".yggghgglggghglgggy.",
    ".yghggggllgggglhggy.",
    ".ygggghglgghgglgghy.",
    ".yhgggggllgggglgggy.",
    ".ygghgggllghggllgghy",
    ".ygggggglggggglgggy.",
    ".yghgggglggghglghgy.",
    "..yyyyyyyyyyyyyyyy..",
    "m.m..............m.m",
  ] },
  meadow_moles: { pal: {"d": "#8a4f3a", "m": "#c7714f", "t": "#ffb38a", "h": "#2a1620", "w": "#9a88ad", "k": "#1a1024", "n": "#ff79c6", "c": "#f5dcec", "g": "#8fe8c0"}, rows: [
    ".............www..............",
    "............wwwww.............",
    "...........wkwwwkw............",
    "...........wwwnwww............",
    "...........cwdddwc............",
    "...ddd.....ddhhhdd......ddd...",
    ".ddmmmdd..dmmmmmmmdd..ddmmmdd.",
    "dmmtmmmmddmtmmmmmmmmddmmtmmmmd",
    "gmgmmmmmdgmmmmmgmgmmddmgmmgmgd",
  ] },
  meadow_kite: { pal: {"o": "#4f9c7c", "m": "#8fe8c0", "w": "#c9f7e2", "t": "#9c7a3c", "r": "#c7714f", "k": "#a64f81", "p": "#ff79c6", "q": "#ffd1ea", "b": "#8be9fd", "s": "#f5dcec"}, rows: [
    ".................k....",
    "................kpk...",
    ".......ooooooo.kpqpk..",
    ".....oommmmmmmokpppk..",
    "....ommmwmmmmmmokpk...",
    "...ommwwmmmmmmmmokb...",
    "..ommmmmmmmmmmmmmos...",
    "..ommmmmmmmmmmmmmmsb..",
    ".ommmmmmmmmmmmmmmmos..",
    ".ommmmmmmmmmmmmmmmo.b.",
    ".ommmmmmmmmmmmmmmmo.s.",
    "..ommmmmmmmmmmmmmo..s.",
    "..oommmmmmmmmmmmoo..b.",
    "....oooommmmoooo......",
    ".......ootroo.........",
    "........trr...........",
    "........trr...........",
    "........trr...........",
    "........trr...........",
    ".......ttrrr..........",
    "..m.m.trrrrrr.m.m.....",
  ] },
  woods_mushrooms: { glow: true, pal: {"p": "#ff79c6", "s": "#a64f81", "c": "#8be9fd", "b": "#4fa9c9", "w": "#f5dcec", "t": "#c9b8d9", "u": "#9a88ad", "y": "#ffe08a", "m": "#8fe8c0"}, rows: [
    "........y...........",
    "....y......cccc.....",
    "..pppp....cwcccc..y.",
    ".pwpppp..cccccwcc...",
    "pppppwpp.bbbbbbbb...",
    "ssssssss...tt.......",
    "...tt......tu..pp...",
    "...tu.....ttu.pwpp..",
    "..ttu.y...tu..ssss..",
    "..tu......tu...tu...",
    "m.tu.m...mtu.m.tu.m.",
    ".mm.m.m.m.mm.m.mm.m.",
  ] },
  woods_owl: { pal: {"o": "#6f588c", "l": "#c9a0ff", "w": "#e8d6ff", "y": "#ffe08a", "k": "#1a1024", "n": "#ffb38a", "t": "#9c7a3c", "h": "#d9b565", "r": "#c7714f", "d": "#8a4f3a", "c": "#8be9fd", "s": "#fff1e6", "m": "#8fe8c0"}, rows: [
    ".................rrr..",
    "..o.....o........rdr..",
    "..oo...oo........rdr..",
    "..ooooooo........rdr..",
    "..olllllllo......rdr..",
    ".oyyylllllo......rdr..",
    ".oykylooolo......rdr..",
    ".oyyylllllo......rdr..",
    ".olllnlllo.......rdr..",
    ".ollwlwlwlo.s....rdr..",
    ".olwlwlwlloscs...rdr..",
    "..ollwlwllt.c.t..rdr..",
    "...ollllo.thhht..rdr..",
    "rrrnrrnrrrrrrrrrrrdr..",
    ".rdddddddddddddddddr..",
    "rrrrrrrrrrrrrrrrrrdr..",
    ".................rdr..",
    ".................rdr..",
    "...............rrdddrr",
    "..............rrdddddr",
    "m.m.........m.m.m.....",
  ] },
});
